# Site settings
title: Jinghao Niu | CASIA
email: niujinghao2015@ia.ac.cn
description: > # this means to ignore newlines until "baseurl:"
  Jinghao.Niu | CASIA
baseurl: "/Jinghao.Niu" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: windniu
github_username:  windniu

# Build settings
markdown: kramdown
